import argparse
from pathlib import Path

from motion_graph.viewer import serve


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Serve a motion graph viewer with Flask."
    )
    parser.add_argument(
        "-g",
        "--motion-graph",
        required=True,
        help="path to motion_graph.json",
    )
    parser.add_argument(
        "--mode",
        choices=("graph", "image"),
        default="graph",
        help="graph only or graph with rendered frame preview",
    )
    parser.add_argument(
        "--image-manifest",
        action="append",
        default=None,
        help="manifest.json generated by render_image_library.py; repeat to show multiple image libraries side by side",
    )
    parser.add_argument(
        "--host",
        default="127.0.0.1",
        help="host for the Flask server",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=8765,
        help="port for the Flask server",
    )
    parser.add_argument(
        "--fps",
        type=float,
        default=24.0,
        help="logical playback fps for the walker",
    )
    return parser


def main() -> None:
    args = build_parser().parse_args()
    serve(
        graph_path=Path(args.motion_graph),
        host=args.host,
        port=args.port,
        mode=args.mode,
        image_manifests=None if args.image_manifest is None else [Path(item) for item in args.image_manifest],
        fps=args.fps,
    )


if __name__ == "__main__":
    main()
